apiVersion: v1
kind: Service
metadata:
  name: fppr-service
spec:
  selector:
    app: fppr-hive  # Change this to expose the correct service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
