apiVersion: apps/v1
kind: Deployment
metadata:
  name: fppr-hive
  labels:
    app: fppr-hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fppr-hive
  template:
    metadata:
      labels:
        app: fppr-hive
    spec:
      containers:
      - name: hive
        image: fppr-hive:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fppr-hive-service
spec:
  type: NodePort
  selector:
    app: fppr-hive
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500  # Ensuring it's accessible remotely
