apiVersion: apps/v1
kind: Deployment
metadata:
  name: fppr-hive
  labels:
    app: fppr-hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fppr-hive
  template:
    metadata:
      labels:
        app: fppr-hive
    spec:
      containers:
      - name: hive
        image: fppr-hive:latest  # Use locally built image
        imagePullPolicy: IfNotPresent  # Ensure Kubernetes does not pull from an external registry
        ports:
        - containerPort: 5000
