global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fppr-nodes'
    static_configs:
      - targets:
          - 'fppr-hive-service:5000'
          - 'fppr-member-service:5000'

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9091'  # ✅ Change 9090 to 9091
