apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9091  # ✅ Change 9090 to 9091
      targetPort: 9091
      nodePort: 30191  # Adjust as needed
  selector:
    app: prometheus
